WTF_CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'
# UPLOAD_FOLDER = '/home/shiva/Desktop/ocr/idiginfo-ocr/images/'
# OUTPUT_FOLDER = '/home/shiva/Desktop/ocr/idiginfo-ocr/ocrd/'
# BATCHSUBMITED = '/home/shiva/Desktop/ocr/idiginfo-ocr/batchsubmited/'
# BATCHPROCESSED = '/home/shiva/Desktop/ocr/idiginfo-ocr/batchprocessed/'
UPLOAD_FOLDER = '/home/si13f/idiginfo-ocr/images/'
OUTPUT_FOLDER = '/home/si13f/idiginfo-ocr/ocrd/'
BATCHSUBMITED = '/home/si13f/idiginfo-ocr/batchsubmited/'
BATCHPROCESSED = '/home/si13f/idiginfo-ocr/batchprocessed/'
ALLOWED_EXTENSIONS = set(['jpg'])
ALLOWED_JSON_EXTENSIONS = set(['json'])
PROPAGATE_EXCEPTIONS = True
